---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    author: maruti
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-container
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-file
                  key: a

...    
