---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-latest
  labels:
    app: nginx-app
    author: maruti
spec:
  selector: 
    matchLabels:
      app: nginx-latest
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-latest
    spec:
      containers:
        - name: nginx-pod
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8089
          resources:
            requests:
              cpu: 100m
              memory: 150M
            limits:
              cpu: 200m
              memory: 200M
...
