apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: mydb
    author: maruti
spec:
  containers:
    - name: postgres-container
      image: postgres
      ports:
        - containerPort: 5432
          hostPort: 8080
      env:
        - name: POSTGRES_USER
          value: maruti
        - name: POSTGRES_PASSWORD
          value: maruti
        - name: POSTGRES_DB
          value: mydb
