---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  labels:
    type: web-server
    author: maruti
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: httpd-app
  template:
    metadata:
      name: httpd-pod
      labels:
        app: httpd-app
    spec:
      containers:
        - name: httpd-container
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8088
          resources: # by using resources components we can able to set cpu and memory utilization size as per our requirement
            requests:
              cpu: 100m
              memory: 150M
            limits:
              cpu: 200m
              memory: 200M
...
