---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    author: maruti
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 8090
      nodePort: 30001
  selector:
      app: mynginx
      author: maruti
...

