---
apiVersion: v1
kind: Service
metadata:
  name: httpd-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30003
  selector:
    app: myhttpd1
    author: maruti
...
