---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    app: mydb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    author: maruti
spec:
  replicas: 2
  serviceName: mysql
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mydb
    spec:
      containers:
       - name: mysql-container
         image: mysql
         env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: mysql-secret
                  key: a
         volumeMounts:
          - name: myvolume-storage
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
          - metadata:
              name: myvolume-storage
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1G
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  a: maruti
...
