---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-nginx
  labels:
    author: maruti
spec:
      containers:
        - name: nginx-app
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
      tolerations:
        - key: node1
          value: maruti1
          operator: Equal
          effect: NoSchedule
...
