---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    author: maruti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisapp
  template:
    metadata:
      name: redis-pod
      labels:
        app: redisapp
    spec:
      containers:
        - name: redis-container
          image: redis
...
